### ISSUE TITLE
Mount volume to fargate

### ISSUE THREAD

**Issue by gshettytcs** [cn-terraform/terraform-aws-jenkins#1]
Hi,

Thanks for the template, this is veryhelpfull. I had one doubt in the jenkins master configuration. Where will the Jenkins master file be stored ? When we use EC2 we mount a EFS to teh docker container, so that all data gets copied to EFS and when i restart eh Jenkins master Image i can mount the same EFS so that it will pick the configurations. In fargate how do we do it ?

**Comment by jnonino** [comment]
This is something I have pending on this project. The idea was to use Fargate to deploy de containers. But at that time, I found out that with Fargate you cannot mount EFS. So I leave this template like that but this is not completely finish. I was waiting for AWS to allow to mount EFS on Fargate instead of refactoring this code to go back to ECS using EC2 launch type.

**Comment by gshettytcs** [comment]
Thanks jnonino

**Comment by jnonino** [comment]
Hi, recently AWS enabled the feature. I'll start working on this next week. I will send you the new version when it is ready. Thanks

**Comment by luvs** [comment]
Hi! Thanks for your modules!

I tried to uncomment your code for attach volume, but when task starts i have error "failed to invoke EFS utils commands to set up EFS volumes: stderr: mount.nfs4: mounting fs-0124b682.efs.us-east-1.amazonaws.com:/var/jenkins_home failed, reason given by server: No such file or directory".

Maybe you know how I can fix it?

**Comment by jnonino** [comment]
Hi, thanks!
Yes, there is an error on mounting volumes to the fargate task. I have to work on that. That's why I have this ticket opened. I didn't have time yet to enable this feature.

**Comment by next-beatrizmartindiaz** [comment]
Good afternoon,
Thank you very much for your module. I have verified that the issue you are talking about is already solved. However, and tried to fix the EFS problem without success. Have you managed to solve this problem?
Thank you very much
