### ISSUE TITLE
Fails to create the loadbalancer if you only give it private IPs

### ISSUE THREAD

**Issue by sean-abbott** [cn-terraform/terraform-aws-jenkins#3]
I have no need to put this on the public internet, so I would like to do this using purely internal subnets. 

however, when I pass an empty list to the public subnets, I get 
```
Error: Error creating application Load Balancer: ValidationError: At least two subnets in two different Availability Zones must be specified
	status code: 400, request id: e60ff5b6-b39d-4f0a-9d9c-bbac15916143

  on .terraform/modules/jenkins.ecs-alb/terraform-aws-ecs-alb-1.0.2/main.tf line 15, in resource "aws_lb" "lb":
  15: resource "aws_lb" "lb" {
```

Also, running this with a mangled local copy (which handles the loadbalancer itself), I get 
```
container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/var/run/netns/8c63af76dd0a40eeba68e208d1895761\" caused \"lstat /var/run/netns/8c63af76dd0a40eeba68e208d1895761: no such file or directory\""
```

Which is probably not an issue with this just curious if anyone else has seen that.

**Comment by jnonino** [comment]
Hi, sorry for the late response. You need to set the variable `internal` in true. That ways the load balancer will be created using the subnets in variable `private_subnets`.
If ` internal` is false, the load balancer will be created on subnets indicated in `public_subnets`.

Hope this helps and sorry again for the late response.
