### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by asethi19** [cn-terraform/terraform-aws-jenkins#5]
module.jenkins.module.ecs-fargate-service.aws_security_group_rule.ingress_through_http["8080"]: Creation complete after 0s [id=sgrule-542379680]
module.jenkins.module.ecs-fargate-service.aws_security_group_rule.ingress_through_http["5000"]: Creation complete after 1s [id=sgrule-1272381205]

**Error**: Provider produced inconsistent final plan

When expanding the plan for
module.jenkins.module.ecs-fargate-service.aws_ecs_service.service to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.load_balancer: block set length changed from 1 to 2.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by asethi19** [comment]
@jnonino..can you suggest any workaround for this issue ? Appreciate your help on this.

**Comment by jnonino** [comment]
Hi, I'm closing this issue as it has been a long time without new reports. If you find this is still happening, please reopen.
